### PR TITLE
Add apple clang 9.1 job on travis file [build=outdated]

### PR DESCRIPTION
**Pull request by uilianries**

### CODE REVIEW

**Comment by SSE4** [comment]
@uilianries  CI error is weird: 
```
Traceback (most recent call last):
  File "build.py", line 10, in <module>
    builder.run()
  File "C:\Python27\lib\site-packages\cpt\packager.py", line 328, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "C:\Python27\lib\site-packages\cpt\packager.py", line 404, in run_builds
    r.run()
  File "C:\Python27\lib\site-packages\cpt\runner.py", line 72, in run
    profile_name=self._profile_abs_path)
  File "C:\Python27\lib\site-packages\conans\client\conan_api.py", line 76, in wrapper
    return f(*args, **kwargs)
  File "C:\Python27\lib\site-packages\conans\client\conan_api.py", line 328, in create
    test_build_folder, test_folder, conanfile_path)
  File "C:\Python27\lib\site-packages\conans\client\cmd\create.py", line 40, in create
    test_build_folder=test_build_folder)
  File "C:\Python27\lib\site-packages\conans\client\cmd\test.py", line 39, in install_build_and_test
    keep_build=keep_build)
  File "C:\Python27\lib\site-packages\conans\client\manager.py", line 385, in install
    installer.install(deps_graph, profile.build_requires, keep_build, update=update)
  File "C:\Python27\lib\site-packages\conans\client\installer.py", line 247, in install
    root_node, update)
  File "C:\Python27\lib\site-packages\conans\client\installer.py", line 318, in _build
    keep_build, profile_build_requires, flat, deps_graph, update)
  File "C:\Python27\lib\site-packages\conans\client\installer.py", line 377, in _build_package
    raise exc
conans.errors.ConanExceptionInUserConanfileMethod: vorbis/1.3.5@bincrafters/testing: Error in build() method, line 100
	self.build_with_visual_studio()
while calling 'build_with_visual_studio', line 72
	sln_filename = update_projects_in_solution(sln_folder, self.options.shared)
while calling 'update_projects_in_solution', line 67
	tools.save(path, updated_content)
	UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)
Command exited with code 1
```

given the fact \ufeff is BOM (Byte Order Mask), it seems like conan's helper `tools.save` is having problems on saving unicode files with BOM, which are pretty common on Windows.
/cc @lasote @memsharded

**Comment by uilianries** [comment]
I would say that is a new bug, because I just re-started the latest build on Appveyor and on last time this package passed with success. I'm on mobile now, but I'll post the logs later

**Comment by lasote** [comment]
Investigating

**Comment by memsharded** [comment]
Works in 1.1.1, fails in 1.2.3 and later.

**Comment by memsharded** [comment]
Identified issue, it was a double error negating itself and eventually working. Pylint was changing the default encoding to utf8. Pylint was removed in 1.2, so the default encoding is ascii now, and that can't handle well unicode characters.

**Comment by lasote** [comment]
Please, relaunch this build. We released 1.3.3 yesterday fixing this issue.

**Comment by SSE4** [comment]
conan issue is gone, however, other errors appeared. I am looking at em.

**Review by SSE4 — APPROVED** [review]
LGTM

**Pull request merged**
