### PR TITLE
Applied conventions on testing/1.3.6

### PR DESCRIPTION
**Pull request by madebr**
Hello,

`bincrafters-conventions` and `conan-readme-generator` were executed on the branch testing/1.3.6

### CODE REVIEW

**Comment by Croydon** [comment]
@madebr Please don't run conan-readme-generator anymore for further pull requests, I believe we need first another discussion about the structure of our readme

conan-readme-generator did grow because of the way conan-community did write their readmes, but in bincrafters we have way too many recipes and some of us think that this is too much work for nothing to constantly regenerate readmes

**Comment by madebr** [comment]
@croydon Ok. I will limit my script to running the `bincrafters-conventions` script.

**Comment by madebr** [comment]
@Croydon:
This should work now (at least if my the conan-ogg pull has been merged to stable branch, built and uploaded to bintray).

**Comment by madebr** [comment]
@Croydon 
I have added a test for missing `.github/settings.yml` file to bincrafters-conventions: https://github.com/madebr/bincrafters-repo-bincrafters-conventions/blob/check_settings_yml/bincrafters_conventions/actions/check_for_github_settings_yml.py

How would you auto fix it? In the conventions tool or in conan-readme-generator?

**Comment by Croydon** [comment]
> How would you auto fix it? In the conventions tool or in conan-readme-generator?

Not at all. Despite its name bincrafters-conventions, and our other tools in general as well, are pretty generic and can be used by non-bincrafters as well. I would like that it stays that way

These GitHub settings are very specific to GitHub's platform, the specific GitHub app and Bincrafter's workflow

**Pull request merged**
